version: "3.9"

services:
  app:
    build:
      context: .
    image: nn-serv:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace:ro
    environment:
      - APP_MODULE=src.main:app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    command: ["sh", "-c", "uvicorn ${APP_MODULE:-src.main:app} --host 0.0.0.0 --port 8000"]
